### ISSUE TITLE
Feature request: Derived key from hash (IDKey)

### ISSUE THREAD

**Issue by alfonmga** [alexedwards/argon2id#12]
It would be helpful to add a method to derive keys from hashes.

Proposed method spec:

```go
func IDKeyFromHash(hash string, keyLen uint32) []byte
```

https://pkg.go.dev/golang.org/x/crypto/argon2#IDKey

**Comment by alfonmga** [comment]
I didn't saw [DecodeHash](https://github.com/alexedwards/argon2id/blob/master/argon2id.go#L144) method before creating this issue. Be free to close this issue if you think maybe it's out of scope for this package.

Thanks for your work BTW ;-)

**Comment by alexedwards** [comment]
Sorry for the slow reply. Like you say, I think it's easy enough to achieve this by using `DecodeHash` so I'll close the issue.
