### ISSUE TITLE
DecodeHash must check if hashed password uses argon2id

### ISSUE THREAD

**Issue by constb** [alexedwards/argon2id#13]
[DecodeHash](https://github.com/alexedwards/argon2id/blob/master/argon2id.go#L144) goes straight to decoding argon2id params without checking first if `vals[1] == "argon2id"`. I think this check is required and a meaningful error must be returned if wrong hash type is provided.

**Comment by alexedwards** [comment]
Good spot, thanks. I've pushed commit b3bf4bb8cbbf75de9aa4cc45382e7356611204af which now returns an `ErrIncompatibleVariant` error if the hash uses a variant that isn't equal to `argon2id`
