### ISSUE TITLE
To big memory consumption

### ISSUE THREAD

**Issue by Shamil-R** [alexedwards/argon2id#17]
One CreateHash function consumes a lot of resources. Because there is code in func initBlocks
`var block0 [1024]byte
 B := make([]block, memory)`

	
Maybe optimize it?

**Comment by kirides** [comment]
without looking into it: argon2id and other hashing algorithms make use of "memory" as a security measurement, to fight specialized hardware and attack cost.

They _should_ be "slow" and "expensive" relative to their benefit. On a Server, 100ms and 1 MB for a login-hash _might_ be okay. Storing the hashes locally though requires _a lot_ more. typically 1000ms and 4-16 MB per try or even higher.

_this is NOT professional advice, nor do i recommend these values. Please lookup the correct up-to-date values for your used hashing algorithm up_

**Comment by pierow2k** [comment]
The [IETF Internet-Draft](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-argon2-04#section-4) referenced in the [README.md](https://github.com/alexedwards/argon2id/blob/master/README.md) doc speaks to setting the Argon parameters according to the maximum amount memory that each call can _afford_.

**Comment by alexedwards** [comment]
Please see this response to a similar issue: https://github.com/alexedwards/argon2id/issues/3#issuecomment-548490682

Argon2 is deliberately memory hungry by design. Please change the default parameters to suit your needs and hardware.
