### ISSUE TITLE
support for pepper?

### ISSUE THREAD

**Issue by G2G2G2G** [alexedwards/argon2id#9]
Right now I append a pepper onto all passwords (especially useful for people using terrible passes)

Was wondering if this can be added to the params?

**Comment by ethanmad** [comment]
@G2G2G2G  In case you didn't know, argon2id supports peppers. Just concatenate password and pepper.

You can compare password and hash like so:
`match, err := argon2id.ComparePasswordAndHash(plaintext+pepper, hasedPassword);`

Hash a password like so:
`hashedPw, err := argon2id.CreateHash(plaintext+pepper, argon2id.DefaultParams);`

**Comment by G2G2G2G** [comment]
Yes I understand that, I said "I append a pepper onto all passwords" which is the same as concatenate. 

was just curious if it was going to be added, but I guess it doesn't matter if he's kinda inactive on it
